const mongoose = require("mongoose");

const StudentSchema = new mongoose.Schema(
    {
        name:{
            type:String,
            required:true,
        },
        email:{
            type:String,
            required:true,
        },
        phoneNo:{
            type:Number,
            required:true,
        },
        state:{
            type:String,
            required:true,
        },
        district:{
            type:String,
            required:true,
        },
        institute:{
            type:String,
            required:true,
        },
        qualification:{
            type:String,
            required:true,
        },
        description:{
            type:String,
            required:true,
        },
        profile:{
            type:String,
            required:true,
        },
        job:{
            type:Object,
            default:{}
        },
        internship:{
            type:Object,
            default:{}
        },
        hackathon:{
            type:Object,
            default:{}
        },
        degree:{
            type:String,
            required:true,
        },
        currentYear:{
            type:Number,
            required:true,
        },
        from:{
            type:String,
            required:true,
        },
        to:{
            type:String,
            required:true,
        },
        achivements:{
            type:String,
            // required:true,
        },
        password:{
            type:String
        }
    },
    { timestamps: true }
    );

module.exports = mongoose.model("Student", StudentSchema);